### ISSUE TITLE
Chinese character garbling

### ISSUE THREAD

**Issue by xihan123** [wei/socialify#227]
It was working fine a while ago, even in preview, but there's a problem with quoting it

envisage:
![0](https://github.com/wei/socialify/assets/44894509/834cf839-df90-4f78-abcf-fe97bc55ca2f)

actual:
![1](https://github.com/wei/socialify/assets/44894509/f24678fd-8fe4-46f4-a85f-355039fa4cf8)

**Comment by wei** [comment]
@xihan123 thanks for the report. It was caused by an update of satori to version 0.10.x. 

I have rolled back for now, when we upgrade in the future, we'll make sure the chinese characters are tested thoroughly!

![QDReadHook](https://socialify.git.ci/xihan123/QDReadHook/image?description=1&forks=1&issues=1&language=1&name=1&owner=1&pulls=1&stargazers=1&theme=Light)
