### ISSUE TITLE
Upgrade to ESLint 9.x

### ISSUE THREAD

**Issue by wei** [wei/socialify#271]
Let's clean up the extraneous eslint plugins and configs we have. The simpler, the better ➖

**Comment by KemingHe** [comment]
Hello @wei, most TypeScript plugins for ESLint 9.X have not come out yet, (speaking from experience, so take it with a grain of salt). On the other hand, I've since switched to BiomeJS and had a blast using it (faster, better CLI visuals, easier setup).

Give it a look: https://biomejs.dev/guides/getting-started/

It's what my mentor Chris https://www.linkedin.com/in/cstroliadavis/ recommended to me. ❤️ 

I'll be happy to do the migration for us. Hear from you soon!!

**Comment by wei** [comment]
@KemingHe thanks for the recommendation 🙌🏻! Will check it out.

**Comment by KemingHe** [comment]
Evening/morning, @wei. I have **good news and updates** about the proposed migration to BiomeJS:

0. Context: ESLint v9+ dropped all built-in formatters, making waiting for TS plugins to come out essential and tedious: 

> https://eslint.org/blog/2024/04/eslint-v9.0.0-released/#removed-all-formatters-except-stylish%2C-html%2C-json%2C-and-json-with-meta

1. In my local build, I've successfully migrated all the prettier/eslint settings to their BiomeJS equivalent.

2. BiomeJS actually offers (optional) stricter formatting and better fixes, i.e.

```typescript
// This is allowed by our current prettier:
<element
  attr1="val1"
  attr2="val2">
</element>

// while in BiomeJS you can opt to force devs to write:
<element
  attr1="val1"
  attr2="val2"
>
</element>
```

3. Besides the formatting discrepancies, linting and the resulting testing, build, and execution behavior are exactly the same.

Let me know your thoughts on whether to move forward with BiomeJS (and have only one config file, no extra plugins, formatter-linter all in one). Hear from you soon. ❤️

**Comment by wei** [comment]
Amazing @KemingHe that's great! Thanks for looking into this. Please create a PR with `npx changeset` (patch release)

**Comment by KemingHe** [comment]
Sure thing, let me clean up a bit and get that PR submitted for review.
