### ISSUE TITLE
Bogged down by 🚨 dependency updates? We could consider containerization and self-hosting on the cloud ☁️ 

### ISSUE THREAD

**Issue by KemingHe** [wei/socialify#296]
Hi @wei, referencing #146 and #274, while considering the constant barrage of dependabot PRs, what's your opinion on Docker-izing this app and deploy to GCP Cloud Run with auto-scaling to zero? 

The expected dependency maintenance will be near zero (everything minus the env vars is deterministic in the container), and the monthly hosting cost will be around $5.

I know exactly what to do if you are interested and want to explore this route,

of course...after the current cards #295 #68 and #272 (second part, the App Router migration). 😃

**Comment by wei** [comment]
Hello @KemingHe , could you help me understand how dependency maintenance will be near zero? We don't **have to** update dependencies with the current deployment either, it's just something we are doing to keep the project in a healthy state.

**Comment by wei** [comment]
We current use Vercel serverless runtime which has a lot of performance benefits over a containerized app.

**Comment by KemingHe** [comment]
> We current use Vercel serverless runtime which has a lot of performance benefits over a dockerized app, are there any advantages dockerized aside have over running on the edge runtime?

Wow, I did not know that (probably for the best since I shouldn't have access to the deployment details). The way I see it is in the long run, Dockerization allows us to:

1. Keep production running regardless of platform availability (Vercel might pull a Heroku someday),
2. Make app distributable, especially as the tech stack ages and people still need the features but not the learning/contrib experience,
3. One of my GCP apps costs <$2 last month total to host with access from anywhere in the world, no distruptions/maintenance, only downside is the cold start, since container is scaled to 0.

Happy to talk more after fixing the bot's mess of a dep bump. 😄 @wei

**Comment by wei** [comment]
Great! I'm open to distribute a docker image for ease of self-deployment but low on the priority list. 

good point on the Code Starts, this is be a deal breaker for Socialify because GitHub only waits up to 3-4 seconds to load images.

We're actually sponsored by Vercel with a generous tier. We can continue to use it for the foreseeable future and change course if anything changes.

Plus it also comes with branch/pr previews which helps with PR reviews quite a bit. (That's how I caught the Daisy UI change without pulling it down myself)
